### PR TITLE
Add missing c_library_flags declaration

### PR DESCRIPTION
**Pull request by leamingrad**
This PR adds a missing flags stanza in the dune file to make it look more like the example at https://dune.readthedocs.io/en/latest/quick-start.html#defining-a-library-with-c-stubs.

In all honesty, I am not 100% about what the exact syntax should be (maybe @NathanReb knows more), but this stops me getting errors when I run `dune utop` for the analyzer.

Potentially we should release a new package with this in, on the off chance that someone else has been trying to do this.

### CODE REVIEW

**Comment by leamingrad** [comment]
Hmm looks like I need to understand this more, as it isn't working as expected. In particular, on my local machine, I did the following (which works happily):

* Make a clean checkout of this repo
* Run `dune build @install`
* Make the change in this PR
* Run `dune install`

**Comment by NathanReb** [comment]
Not sure exactly what's going on here but I'll take a look if I can find some time!

**Comment by emillon** [comment]
This is unfortunately hitting a known limitation of dune: it's not possible to use `dune utop` in the presence of C stubs. I think that the correct pointer is https://github.com/ocaml/dune/issues/108.

**Comment by leamingrad** [comment]
I found that issue before, but my impression from https://github.com/ocaml/dune/issues/108#issuecomment-426211320 was that it should work in our case, as `zxcvbn` is a public library when it is being used as a dependency.

Double checking my local copy, I appear to have flipped my situation: I was previously able to run `dune utop` from my `ocaml-zxcvbn` checkout, but running it from my `analyzer` checkout gave an error, but now I can run it successfully from my `analyzer` checkout and running it from my `zxcvbn` checkout gives an error :confused:

**Comment by leamingrad** [comment]
I've done a bit more digging and I think I understand the situation a lot more now:
* When `zxcvbn` is installed via `opam`, `dune utop` does not work at the analyzer level because it cannot find the stub dynamic library functions
* If I install `zxcvbn` manually using `dune build @install && dune install` from my checkout of master, everything works
* If I install it using `opam install .` from my checkout of master, everything works

If I diff the tree of my `.opam` folder after `opam` install vs `dune` install, there seem to be quite a few differences, both at the "what files are there" level and at the individual file level, but if I diff it after the `opam install .` install it is much closer to the `dune` install.

I think the fix here is actually just to deploy a new version which contains all the build changes that have occurred since the last version.

**Comment by leamingrad** [comment]
The new version has been pushed and `dune utop` now works as expected, so this can close

**Pull request closed without merging**
